codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 2%  # Allow 2% drop without failing
    patch:
      default:
        target: 80%  # New code should have 80% coverage

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
